### ISSUE TITLE
Link to other related projects

### ISSUE THREAD

**Issue by Oreoxmt** [c4pt0r/go-tidbcloud-sdk-v1#2]
Hello c4pt0r! 👋🏼 

[`tidbcloudy`](https://github.com/Oreoxmt/tidbcloudy) is a Python SDK for TiDB Cloud. I have linked to your project in my [README](https://github.com/Oreoxmt/tidbcloudy#related-projects). Would you like adding my project to your README as well? 

Cheers! 🍻

**Comment by c4pt0r** [comment]
No problem :)
